n = input('Digite algo ')
print('Qual é o tipo primitivo? ', type(n))
print('Ele é um númérico? ', n.isnumeric())
print('Só possui espaços? ', n.isspace())
print('É alfabético? ', n.isalpha())
print('É alfanumérico? ', n.isalnum())
